import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, KeyRound, Mail, ShieldCheck } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

const AuthFrame = ({ eyebrow, title, description, children }) => <div className="auth-shell min-h-[calc(100vh-4rem)] flex items-center justify-center px-4 py-12"><div className="auth-panel w-full max-w-md rounded-3xl p-8 md:p-10"><Link to="/login" className="text-sm text-gray-400 hover:text-orange-500 flex items-center gap-2 mb-8"><ArrowLeft className="w-4 h-4" /> Back to sign in</Link><div className="auth-mark mb-5"><ShieldCheck className="w-6 h-6" /></div><p className="eyebrow">{eyebrow}</p><h1 className="auth-title mt-2">{title}</h1><p className="text-sm text-gray-500 mt-3 mb-7">{description}</p>{children}</div></div>;

export const ForgotPassword = () => {
  const { requestPasswordReset } = useAuth(); const [email, setEmail] = useState(''); const [sent, setSent] = useState(false);
  return <AuthFrame eyebrow="Account recovery" title="Reset your password" description="We will send a secure mock reset link to your inbox.">{sent ? <div className="text-center py-4"><CheckCircle2 className="w-12 h-12 text-green-500 mx-auto mb-3" /><p className="font-bold text-gray-900">Reset link sent</p><p className="text-sm text-gray-500 mt-2">Check {email} for the next step.</p></div> : <form onSubmit={(event) => { event.preventDefault(); requestPasswordReset(email); setSent(true); }} className="space-y-4"><label className="block text-sm font-semibold text-gray-700">Email address<input required type="email" value={email} onChange={(event) => setEmail(event.target.value)} className="w-full mt-2 p-3 rounded-xl border border-gray-200 font-normal focus:outline-none focus:border-orange-500" /></label><button className="w-full bg-orange-500 text-white rounded-xl py-3.5 font-bold">Send reset link</button></form>}</AuthFrame>;
};

export const ResetPassword = () => { const navigate = useNavigate(); const [saved, setSaved] = useState(false); return <AuthFrame eyebrow="Account recovery" title="Choose a new password" description="Create a strong password for your BiteExpress account.">{saved ? <div className="text-center py-4"><CheckCircle2 className="w-12 h-12 text-green-500 mx-auto mb-3" /><p className="font-bold">Password updated</p><button onClick={() => navigate('/login')} className="mt-5 text-orange-500 font-bold">Return to sign in</button></div> : <form onSubmit={(event) => { event.preventDefault(); setSaved(true); }} className="space-y-4"><label className="block text-sm font-semibold">New password<input required minLength="6" type="password" className="w-full mt-2 p-3 rounded-xl border border-gray-200 font-normal" /></label><label className="block text-sm font-semibold">Confirm password<input required minLength="6" type="password" className="w-full mt-2 p-3 rounded-xl border border-gray-200 font-normal" /></label><button className="w-full bg-orange-500 text-white rounded-xl py-3.5 font-bold flex justify-center gap-2"><KeyRound className="w-4 h-4" /> Update password</button></form>}</AuthFrame>; };

export const EmailVerification = () => { const { verifyEmail } = useAuth(); const [verified, setVerified] = useState(false); return <AuthFrame eyebrow="Almost there" title="Verify your email" description="Enter the six-digit code from your welcome email.">{verified ? <div className="text-center py-4"><CheckCircle2 className="w-12 h-12 text-green-500 mx-auto mb-3" /><p className="font-bold">Email verified</p><Link to="/" className="inline-block mt-5 text-orange-500 font-bold">Start exploring</Link></div> : <form onSubmit={(event) => { event.preventDefault(); setVerified(verifyEmail(event.currentTarget.code.value)); }} className="space-y-4"><label className="block text-sm font-semibold">Verification code<input name="code" required inputMode="numeric" maxLength="6" placeholder="123456" className="w-full mt-2 p-3 rounded-xl border border-gray-200 font-normal tracking-[0.35em]" /></label><button className="w-full bg-orange-500 text-white rounded-xl py-3.5 font-bold flex justify-center gap-2"><Mail className="w-4 h-4" /> Verify email</button></form>}</AuthFrame>; };
