import { useState } from 'react';
import { Activity, ClipboardList, DollarSign, Settings2, Users } from 'lucide-react';
import { usePlatform } from '../../context/PlatformContext';
import { formatCurrency } from '../../utils/currency';

export const AdminOrders = () => {
  const { orders } = usePlatform();
  return <div className="max-w-7xl mx-auto px-4 py-10 space-y-8"><div><p className="text-xs uppercase tracking-[0.18em] text-orange-500 font-bold mb-2">Platform control room</p><h1 className="text-3xl font-bold text-gray-900">Order monitoring</h1></div><div className="grid md:grid-cols-4 gap-5"><Metric label="Total orders" value={orders.length + 1248} icon={<ClipboardList />} /><Metric label="In progress" value={orders.filter((order) => order.status !== 'Delivered').length + 18} icon={<Activity />} /><Metric label="Gross volume" value={formatCurrency(84210)} icon={<DollarSign />} /><Metric label="Customers" value="1,420" icon={<Users />} /></div><div className="bg-white rounded-3xl border border-gray-100 overflow-hidden"><div className="p-5 border-b border-gray-100 font-bold">Live order feed</div>{orders.map((order) => <div key={order.id} className="p-5 border-b border-gray-100 last:border-0 flex flex-col md:flex-row md:items-center justify-between gap-3"><div><p className="font-bold">{order.id} · {order.vendorName}</p><p className="text-sm text-gray-500">{order.customerName} · {order.address}</p></div><div className="flex items-center gap-5"><span className="text-xs font-bold rounded-full px-3 py-1 bg-orange-50 text-orange-700">{order.status}</span><span className="font-bold">{formatCurrency(order.total)}</span></div></div>)}</div></div>;
};

export const AdminSettings = () => {
  const [saved, setSaved] = useState(false);
  return <div className="max-w-5xl mx-auto px-4 py-10 space-y-8"><div><p className="text-xs uppercase tracking-[0.18em] text-orange-500 font-bold mb-2">Platform rules</p><h1 className="text-3xl font-bold text-gray-900">Settings and commission</h1></div><form onSubmit={(event) => { event.preventDefault(); setSaved(true); setTimeout(() => setSaved(false), 1500); }} className="bg-white rounded-3xl border border-gray-100 p-6 md:p-8 space-y-6"><div className="flex items-start gap-4"><Settings2 className="w-6 h-6 text-orange-500 mt-1" /><div><h2 className="font-bold">Commercial settings</h2><p className="text-sm text-gray-500">These controls will map to PlatformSetting in the backend.</p></div></div><label className="block text-sm font-bold text-gray-700">Default commission rate (%)<input type="number" defaultValue="15" min="0" max="100" className="w-full mt-2 p-3 rounded-xl border border-gray-200 font-normal" /></label><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" defaultChecked className="accent-orange-500 w-4 h-4" /> Require vendor approval before publishing</label><label className="flex items-center gap-3 text-sm font-semibold"><input type="checkbox" defaultChecked className="accent-orange-500 w-4 h-4" /> Require delivery verification</label><button className="bg-orange-500 text-white rounded-xl px-5 py-3 font-bold">{saved ? 'Settings saved' : 'Save platform settings'}</button></form></div>;
};

const Metric = ({ label, value, icon }) => <div className="bg-white rounded-2xl border border-gray-100 p-5"><span className="text-orange-500">{icon}</span><p className="text-xs uppercase font-bold text-gray-400 mt-5">{label}</p><p className="text-2xl font-bold text-gray-900 mt-1">{value}</p></div>;
